debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.ssafy.common: debug
    org.springframework.web.service: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
